source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'ResourceManageDemo' do
    pod 'SwiftGen'
    
    script_phase :name => '同步图片', :script => '$PROJECT_DIR/script/AutoAsset $PROJECT_DIR/synchronizeImageFolder $PROJECT_DIR/synchronizeImageFolder_backup $PROJECT_DIR/ResourceManageDemo/Assets.xcassets', :execution_position => :before_compile

    script_phase :name => '生成SwiftGen文件', :script => '$PODS_ROOT/SwiftGen/bin/swiftgen  xcassets $PROJECT_DIR/ResourceManageDemo/Assets.xcassets --templatePath $PROJECT_DIR/script/SwiftGenTemplate.stencil --output $PROJECT_DIR/ResourceManageDemo/Assets.swift', :execution_position => :before_compile
end

